# Generated by Django 5.2.7 on 2025-10-18 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyuser',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('school_faculty', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('highest_qualification', models.CharField(max_length=255)),
                ('area_of_specialization', models.CharField(max_length=255)),
                ('orcid_id', models.CharField(max_length=100)),
                ('scopus_id', models.CharField(max_length=100)),
                ('google_scholar', models.URLField()),
                ('vidwaan_id', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.facultyuser')),
            ],
        ),
    ]
