# Generated by Django 5.2.7 on 2025-11-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_facultyprofile_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='EMP_ID',
            field=models.CharField(max_length=50),
        ),
    ]
