# Generated by Django 5.2.7 on 2025-10-22 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_facultyuser_groups_facultyuser_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_paper', models.CharField(max_length=255)),
                ('author_position', models.CharField(max_length=255)),
                ('corresponding_author', models.CharField(max_length=255)),
                ('journal_name', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('issn', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('issue', models.CharField(blank=True, max_length=50, null=True)),
                ('page_no', models.CharField(blank=True, max_length=50, null=True)),
                ('month_of_publication', models.CharField(max_length=50)),
                ('year_of_publication', models.IntegerField()),
                ('indexed_in', models.CharField(choices=[('SCI', 'SCI'), ('SCIE', 'SCIE'), ('Scopus', 'Scopus'), ('WoS', 'Web of Science'), ('ESCI', 'ESCI'), ('UGC', 'UGC'), ('Other', 'Other')], max_length=20)),
                ('other_index', models.CharField(blank=True, max_length=255, null=True)),
                ('impact_factor', models.CharField(blank=True, max_length=50, null=True)),
                ('doi_link', models.URLField(blank=True, null=True)),
                ('funding_acknowledged', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('pdf_upload', models.FileField(upload_to='journal_papers/')),
                ('no_of_other_authors_from_iilm', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved_by_cluster', 'Approved by Cluster Head'), ('rejected_by_cluster', 'Rejected by Cluster Head'), ('approved_by_dean', 'Approved by Dean'), ('rejected_by_dean', 'Rejected by Dean'), ('revision', 'Sent for Revision')], default='submitted', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
