# Generated by Django 5.2.7 on 2025-10-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_journalpublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpublication',
            name='first_author',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
