# Generated by Django 5.2.7 on 2025-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_journalpublication_first_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpublication',
            name='cluster_head_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalpublication',
            name='cluster_head_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Sent for Revision')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='journalpublication',
            name='dean_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalpublication',
            name='dean_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
