# Generated by Django 5.2.7 on 2025-10-24 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_journalpublication_cluster_head_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_paper', models.CharField(max_length=255)),
                ('author_position', models.CharField(max_length=255)),
                ('first_author', models.CharField(max_length=255)),
                ('corresponding_author', models.CharField(max_length=255)),
                ('conference_name', models.CharField(max_length=255)),
                ('organizing_body', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=50)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('date_of_presentation', models.DateField()),
                ('doi_link', models.URLField(blank=True, null=True)),
                ('indexed_in', models.CharField(choices=[('SCI', 'SCI'), ('SCIE', 'SCIE'), ('Scopus', 'Scopus'), ('WoS', 'Web of Science'), ('ESCI', 'ESCI'), ('UGC', 'UGC'), ('Other', 'Other')], max_length=20)),
                ('other_index', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_acknowledged', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('pdf_upload', models.FileField(upload_to='conference_papers/')),
                ('no_of_other_authors_from_iilm', models.PositiveIntegerField(default=0)),
                ('cluster_head_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Sent for Revision')], default='pending', max_length=30)),
                ('cluster_head_remarks', models.TextField(blank=True, null=True)),
                ('dean_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('dean_remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved_by_cluster', 'Approved by Cluster Head'), ('rejected_by_cluster', 'Rejected by Cluster Head'), ('approved_by_dean', 'Approved by Dean'), ('rejected_by_dean', 'Rejected by Dean'), ('revision', 'Sent for Revision')], default='submitted', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
