# Generated by Django 5.2.7 on 2025-10-24 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_conferencepublication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('funding_agency', models.CharField(max_length=255)),
                ('principal_investigator', models.CharField(max_length=255)),
                ('co_pi', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_sanctioned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_from', models.DateField()),
                ('duration_to', models.DateField()),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Submitted', 'Submitted')], max_length=20)),
                ('outcome', models.CharField(choices=[('Publication', 'Publication'), ('Patent', 'Patent'), ('Product', 'Product')], max_length=20)),
                ('sanctioned_letter', models.FileField(upload_to='research_projects/')),
                ('no_of_other_authors_from_iilm', models.PositiveIntegerField(default=0)),
                ('cluster_head_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Sent for Revision')], default='pending', max_length=30)),
                ('cluster_head_remarks', models.TextField(blank=True, null=True)),
                ('dean_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('dean_remarks', models.TextField(blank=True, null=True)),
                ('overall_status', models.CharField(choices=[('submitted', 'Submitted'), ('approved_by_cluster', 'Approved by Cluster Head'), ('rejected_by_cluster', 'Rejected by Cluster Head'), ('approved_by_dean', 'Approved by Dean'), ('rejected_by_dean', 'Rejected by Dean'), ('revision', 'Sent for Revision')], default='submitted', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
