# Generated by Django 5.2.7 on 2025-10-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_researchproject_overall_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproject',
            name='status1',
        ),
        migrations.AddField(
            model_name='researchproject',
            name='overall_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved_by_cluster', 'Approved by Cluster Head'), ('rejected_by_cluster', 'Rejected by Cluster Head'), ('approved_by_dean', 'Approved by Dean'), ('rejected_by_dean', 'Rejected by Dean'), ('revision', 'Sent for Revision')], default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('On Hold', 'On Hold')], max_length=20),
        ),
    ]
