# Generated by Django 5.2.7 on 2025-10-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_researchproject_status1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchproject',
            old_name='sanctioned_letter',
            new_name='pdf_upload',
        ),
    ]
