# Generated by Django 5.2.7 on 2025-10-24 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_sanctioned_letter_researchproject_pdf_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_patent', models.CharField(max_length=255)),
                ('inventors', models.TextField()),
                ('patent_number', models.CharField(max_length=100)),
                ('patent_status', models.CharField(choices=[('filed', 'Filed'), ('published', 'Published'), ('granted', 'Granted')], max_length=20)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('date_granted', models.DateField(blank=True, null=True)),
                ('jurisdiction', models.CharField(choices=[('india', 'India'), ('international', 'International')], max_length=20)),
                ('patent_type', models.CharField(choices=[('utility', 'Utility'), ('design', 'Design'), ('process', 'Process')], max_length=20)),
                ('pdf_upload', models.FileField(upload_to='patents/')),
                ('other_authors_count', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('cluster_head_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Sent for Revision')], default='pending', max_length=30)),
                ('cluster_head_remarks', models.TextField(blank=True, null=True)),
                ('dean_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('dean_remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved_by_cluster', 'Approved by Cluster Head'), ('rejected_by_cluster', 'Rejected by Cluster Head'), ('approved_by_dean', 'Approved by Dean'), ('rejected_by_dean', 'Rejected by Dean'), ('revision', 'Sent for Revision')], default='submitted', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
