# Generated by Django 5.2.7 on 2025-10-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_patents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patents',
            name='other_authors_count',
        ),
        migrations.AddField(
            model_name='patents',
            name='no_of_other_authors_from_iilm',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
