# Generated by Django 5.2.7 on 2025-10-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_copyright'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copyright',
            old_name='other_authors_count',
            new_name='no_of_other_authors_from_iilm',
        ),
        migrations.RenameField(
            model_name='copyright',
            old_name='upload_copy',
            new_name='pdf_upload',
        ),
    ]
