# Generated by Django 5.2.7 on 2025-10-25 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_other_authors_count_copyright_no_of_other_authors_from_iilm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhdGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_scholar', models.CharField(max_length=255)),
                ('outside_iilm', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('thesis_title', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('supervisor', 'Supervisor'), ('co_supervisor', 'Co-Supervisor')], max_length=20)),
                ('phd_status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20)),
                ('date_of_completion', models.DateField(blank=True, null=True)),
                ('other_supervisors', models.TextField(blank=True, null=True)),
                ('pdf_upload', models.FileField(upload_to='phd_guidance/')),
                ('no_of_other_authors_from_iilm', models.PositiveIntegerField(default=0)),
                ('cluster_head_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Sent for Revision')], default='pending', max_length=30)),
                ('cluster_head_remarks', models.TextField(blank=True, null=True)),
                ('dean_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('dean_remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved_by_cluster', 'Approved by Cluster Head'), ('rejected_by_cluster', 'Rejected by Cluster Head'), ('approved_by_dean', 'Approved by Dean'), ('rejected_by_dean', 'Rejected by Dean'), ('revision', 'Sent for Revision')], default='submitted', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
