# Generated by Django 5.2.7 on 2025-10-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_phdguidance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phdguidance',
            name='phd_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('thesis_submitted', 'Thesis Submitted'), ('awarded', 'Awarded'), ('discontinued', 'Discontinued')], max_length=20),
        ),
    ]
