# Generated by Django 5.2.7 on 2025-10-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_phdguidance_phd_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phdguidance',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('co_supervisor', 'Co-Supervisor'), ('advisor', 'Advisor'), ('committee_member', 'Committee Member')], max_length=20),
        ),
    ]
