# Generated by Django 5.2.7 on 2025-10-25 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_booksauthored'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('industry_partner', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('role', models.CharField(max_length=100)),
                ('outcomes', models.TextField()),
                ('mou_signed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('no_of_other_authors_from_iilm', models.PositiveIntegerField(default=0)),
                ('pdf_upload', models.FileField(upload_to='consultancy_projects/')),
                ('cluster_head_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Sent for Revision')], default='pending', max_length=30)),
                ('cluster_head_remarks', models.TextField(blank=True, null=True)),
                ('dean_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('dean_remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved_by_cluster', 'Approved by Cluster Head'), ('rejected_by_cluster', 'Rejected by Cluster Head'), ('approved_by_dean', 'Approved by Dean'), ('rejected_by_dean', 'Rejected by Dean'), ('revision', 'Sent for Revision')], default='submitted', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
