# Generated by Django 5.2.7 on 2025-10-26 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_reviewerroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_award', models.CharField(max_length=255)),
                ('awarding_body', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('institutional', 'Institutional'), ('state', 'State'), ('national', 'National'), ('international', 'International')], max_length=30)),
                ('date', models.DateField()),
                ('nature_of_contribution', models.TextField()),
                ('pdf_upload', models.FileField(upload_to='awards_achievements/')),
                ('cluster_head_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Sent for Revision')], default='pending', max_length=30)),
                ('cluster_head_remarks', models.TextField(blank=True, null=True)),
                ('dean_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('dean_remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved_by_cluster', 'Approved by Cluster Head'), ('rejected_by_cluster', 'Rejected by Cluster Head'), ('approved_by_dean', 'Approved by Dean'), ('rejected_by_dean', 'Rejected by Dean'), ('revision', 'Sent for Revision')], default='submitted', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
