# Generated by Django 5.2.7 on 2025-10-26 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_awardsachievements'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=255, verbose_name='Industry / Organization Name')),
                ('nature_of_collaboration', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('outcomes', models.CharField(help_text='(e.g., Internship / Research / Product / Course Developed)', max_length=255)),
                ('mou_signed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('pdf_upload', models.FileField(upload_to='industry_collaboration/')),
                ('cluster_head_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Sent for Revision')], default='pending', max_length=30)),
                ('cluster_head_remarks', models.TextField(blank=True, null=True)),
                ('dean_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('dean_remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved_by_cluster', 'Approved by Cluster Head'), ('rejected_by_cluster', 'Rejected by Cluster Head'), ('approved_by_dean', 'Approved by Dean'), ('rejected_by_dean', 'Rejected by Dean'), ('revision', 'Sent for Revision')], default='submitted', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
