# Generated by Django 5.2.7 on 2025-10-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_industrycollaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyuser',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('dean', 'Dean'), ('cluster_head', 'Cluster Head')], default='faculty', max_length=20),
        ),
    ]
