# Generated by Django 5.2.7 on 2025-10-31 12:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalpublication',
            name='pdf_upload',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
