# Generated by Django 5.2.7 on 2025-10-31 12:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_journalpublication_pdf_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencepublication',
            name='pdf_upload',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
