# Generated by Django 5.2.7 on 2025-10-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_conferencepublication_pdf_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencepublication',
            name='pdf_upload',
            field=models.FileField(upload_to='conference_publications/'),
        ),
        migrations.AlterField(
            model_name='journalpublication',
            name='pdf_upload',
            field=models.FileField(upload_to='journal_publications/'),
        ),
    ]
